version: '3.7'

services:   
  naming-server:
    image: srvivek/b6-naming-service:0.0.1-SNAPSHOT
    mem_limit: 800m
    ports:
      - "8761:8761"
    networks:
      - currency-network
  
  currency-exchange:
    image: srvivek/d2-zipkin-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 800m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  currency-conversion:
    image: srvivek/d3-zepkin-currency-conversion-service-openfeign:0.0.1-SNAPSHOT
    mem_limit: 800m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  api-gateway:
    image: srvivek/d4-zepkin-api-gateway-routes:0.0.1-SNAPSHOT
    mem_limit: 800m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      
  zipkin-server:
    image: openzipkin/zipkin
    mem_limit: 800m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always #Restart if there is a problem starting up

networks:
  currency-network: