apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-01-01T16:33:05Z"
  generation: 1
  labels:
    app: currency-exchange-service
  name: currency-exchange-service
  namespace: default
  resourceVersion: "42362"
  uid: 0c696bec-0c3a-4707-8021-74fa8e541b1c
spec:
  progressDeadlineSeconds: 600
  replicas: 2 # 2 instances should be available
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-exchange-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-exchange-service
    spec:
      containers:
      - image: srvivek/e2-currency-exchange-service-kubernetes:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: e2-currency-exchange-service-kubernetes
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-01-01T16:33:06Z"
    lastUpdateTime: "2025-01-01T16:33:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-01-01T16:33:05Z"
    lastUpdateTime: "2025-01-01T16:33:06Z"
    message: ReplicaSet "currency-exchange-service-5bf8dd7984" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2025-01-01T15:51:02Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-exchange-service
  name: currency-exchange-service
  namespace: default
  resourceVersion: "14833"
  uid: aac3280b-dc3f-4573-881d-a09e318ceb7d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.226.121
  clusterIPs:
  - 34.118.226.121
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30158
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-exchange-service
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.70.41.156
      ipMode: VIP
